#!/usr/bin/env python3
"""
claude_proxy.py - OpenAI-compatible proxy for the Claude Code CLI.

Exposes /v1/chat/completions and /v1/models as a drop-in replacement for the
OpenAI Chat Completions API. All LLM calls go through the Claude Code CLI
subprocess - no Anthropic API is called directly.

Authentication uses the OpenAI wire format: clients pass
`Authorization: Bearer <key>`, where <key> matches the API_KEY env var
(typically loaded from .env, generated by generate_api_key.py).

Session continuity is keyed on the SHA-256 of the system prompt. The
first completion with a given system prompt starts a new Claude session;
the session_id captured from the CLI's result event is cached in memory
(LRU, TTL-bounded), and subsequent requests with the same system prompt
pass --resume <id>. Different system prompts always start fresh sessions.
"""
from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import os
import re
import secrets
import time
import uuid
from collections import OrderedDict
from typing import Any, AsyncIterator, Dict, List, Optional, Tuple

from fastapi import FastAPI, Header, Request
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# .env loader (stdlib-only, runs before env vars are read)
# ---------------------------------------------------------------------------


def _load_env_file(path: str = ".env") -> None:
    if not os.path.exists(path):
        return
    try:
        with open(path, "r", encoding="utf-8") as f:
            for raw in f:
                line = raw.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                k = k.strip()
                v = v.strip()
                if (v.startswith('"') and v.endswith('"')) or (
                    v.startswith("'") and v.endswith("'")
                ):
                    v = v[1:-1]
                os.environ.setdefault(k, v)
    except OSError:
        pass


_load_env_file()


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

CLAUDE_BIN: str = os.environ.get("CLAUDE_BIN", "claude")
DEFAULT_MODEL: str = os.environ.get("DEFAULT_MODEL", "claude-sonnet-4-6")
LOG_LEVEL: str = os.environ.get("LOG_LEVEL", "INFO").upper()
LOG_PROMPTS: bool = os.environ.get("LOG_PROMPTS", "false").lower() == "true"

API_KEY: str = os.environ.get("API_KEY", "").strip()

CLI_TIMEOUT_SECONDS: float = float(os.environ.get("CLI_TIMEOUT_SECONDS", "300"))
MAX_REQUEST_BYTES: int = int(os.environ.get("MAX_REQUEST_BYTES", str(10 * 1024 * 1024)))
MAX_SYSTEM_PROMPT_BYTES: int = int(
    os.environ.get("MAX_SYSTEM_PROMPT_BYTES", str(96 * 1024))
)
SESSION_CACHE_SIZE: int = int(os.environ.get("SESSION_CACHE_SIZE", "256"))
SESSION_CACHE_TTL_SECONDS: float = float(
    os.environ.get("SESSION_CACHE_TTL_SECONDS", "3600")
)
MAX_CONCURRENT_CLI: int = int(os.environ.get("MAX_CONCURRENT_CLI", "2"))

_DEFAULT_MODELS: List[str] = [
    "claude-opus-4-7",
    "claude-opus-4-6",
    "claude-sonnet-4-6",
    "claude-haiku-4-5-20251001",
    "claude-opus-4-5-20250929",
    "claude-sonnet-4-5-20250929",
    "claude-sonnet-4-20250514",
    "claude-opus-4-20250514",
    "claude-3-5-sonnet-20241022",
    "claude-3-5-haiku-20241022",
]

_env_models = os.environ.get("CLAUDE_MODELS", "").strip()
CLAUDE_MODELS: List[str] = (
    [m.strip() for m in _env_models.split(",") if m.strip()]
    if _env_models
    else _DEFAULT_MODELS
)

_CLAUDE_MODEL_SET = set(CLAUDE_MODELS)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=LOG_LEVEL,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger("claude_proxy")


def _sanitize_log(value: Any) -> str:
    """Neutralize newlines and other control characters in user-provided values
    before logging, so a crafted request body cannot forge or inject log lines
    (CodeQL py/log-injection). Printable content and tabs are preserved; other
    control characters are replaced with a space. The trailing ``str.replace``
    calls on line breaks are what the CodeQL sanitizer recognizes."""
    text = value if isinstance(value, str) else str(value)
    text = "".join(ch if ch.isprintable() or ch == "\t" else " " for ch in text)
    return text.replace("\r\n", " ").replace("\r", " ").replace("\n", " ")


# ---------------------------------------------------------------------------
# OpenAI-style errors
# ---------------------------------------------------------------------------


class OpenAIError(Exception):
    def __init__(
        self,
        message: str,
        status: int = 400,
        error_type: str = "invalid_request_error",
        code: Optional[str] = None,
        param: Optional[str] = None,
    ) -> None:
        super().__init__(message)
        self.message = message
        self.status = status
        self.error_type = error_type
        self.code = code
        self.param = param

    def to_body(self) -> Dict[str, Any]:
        return {
            "error": {
                "message": self.message,
                "type": self.error_type,
                "code": self.code,
                "param": self.param,
            }
        }


# ---------------------------------------------------------------------------
# Pydantic request models
# ---------------------------------------------------------------------------


class ToolFunction(BaseModel):
    name: str
    description: str = ""
    parameters: Dict[str, Any] = Field(default_factory=dict)


class Tool(BaseModel):
    type: str = "function"
    function: ToolFunction


class ChatRequest(BaseModel):
    model: str = DEFAULT_MODEL
    messages: List[Dict[str, Any]] = Field(min_length=1)
    stream: bool = False
    tools: Optional[List[Tool]] = None
    tool_choice: Optional[Any] = None
    user: Optional[str] = None
    # Accepted but ignored (Claude CLI controls these internally)
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None


# ---------------------------------------------------------------------------
# Session cache
# ---------------------------------------------------------------------------


class _SessionCache:
    def __init__(self, maxsize: int, ttl: float) -> None:
        self._maxsize = maxsize
        self._ttl = ttl
        self._store: "OrderedDict[str, Tuple[str, float]]" = OrderedDict()

    def get(self, key: str) -> Optional[str]:
        entry = self._store.get(key)
        if not entry:
            return None
        session_id, ts = entry
        if time.time() - ts > self._ttl:
            self._store.pop(key, None)
            return None
        self._store.move_to_end(key)
        return session_id

    def put(self, key: str, session_id: str) -> None:
        self._store[key] = (session_id, time.time())
        self._store.move_to_end(key)
        while len(self._store) > self._maxsize:
            self._store.popitem(last=False)

    def invalidate(self, key: str) -> None:
        self._store.pop(key, None)


_session_cache = _SessionCache(SESSION_CACHE_SIZE, SESSION_CACHE_TTL_SECONDS)

# Semaphore to cap concurrent Claude subprocesses. Lazy-initialised on first
# use so it is created inside a running event loop.
_cli_semaphore: Optional[asyncio.Semaphore] = None


def _get_cli_semaphore() -> asyncio.Semaphore:
    global _cli_semaphore
    if _cli_semaphore is None:
        _cli_semaphore = asyncio.Semaphore(MAX_CONCURRENT_CLI)
    return _cli_semaphore


def _session_key(system_prompt: Optional[str], user: Optional[str] = None) -> Optional[str]:
    if not system_prompt:
        return None
    # Include user identifier so different callers with the same system prompt
    # don't share session state (conversation history bleed).
    key_material = f"{user or ''}:{system_prompt}"
    return hashlib.sha256(key_material.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Prompt construction
# ---------------------------------------------------------------------------

_TOOL_BLOCK_TEMPLATE = """\
You are operating as a pure language model via an API. You do NOT have access \
to any built-in tools, filesystem, bash, or code execution. The ONLY way to \
invoke an external capability is to emit a fenced JSON code block as described \
below. Do not attempt to execute anything yourself.

When you want to call one of the available tools, emit EXACTLY this format and \
nothing else - no prose before or after:

```json
{{
  "name": "<tool_name>",
  "arguments": {{
    "<arg>": "<value>"
  }}
}}
```

Rules:
- The key MUST be "arguments" (not "parameters" or any other key).
- Emit ONLY the fenced JSON block - no surrounding text before or after.
- You may emit multiple fenced blocks in sequence to call multiple tools.
- Stop immediately after emitting tool call block(s). Do not narrate or explain.
- If no tool is needed, respond in plain text as normal.
- NEVER say a tool is unavailable or failed - just emit the block and stop.

Available tools:
{tool_specs}
"""


def _content_to_text(content: Any) -> str:
    """Normalise OpenAI message content (str or list of text blocks).

    Raises OpenAIError on unsupported content types (images, audio, etc.).
    """
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: List[str] = []
        for block in content:
            if not isinstance(block, dict):
                raise OpenAIError(
                    f"Unsupported content block: expected object, got {type(block).__name__}",
                    param="messages",
                )
            block_type = block.get("type")
            if block_type == "text":
                parts.append(block.get("text", ""))
            else:
                raise OpenAIError(
                    f"Unsupported content block type {block_type!r}. "
                    "Only 'text' blocks are supported by this proxy.",
                    param="messages",
                )
        return "\n".join(parts)
    raise OpenAIError(
        f"Unsupported content type: {type(content).__name__}",
        param="messages",
    )


def _serialize_assistant_tool_calls(tool_calls: List[Dict[str, Any]]) -> str:
    blocks: List[str] = []
    for tc in tool_calls:
        fn = tc.get("function") or {}
        name = fn.get("name") or "unknown"
        raw_args = fn.get("arguments", "{}")
        if isinstance(raw_args, str):
            try:
                args_obj: Any = json.loads(raw_args) if raw_args else {}
            except json.JSONDecodeError:
                args_obj = {"_raw": raw_args}
        else:
            args_obj = raw_args
        payload = json.dumps({"name": name, "arguments": args_obj}, indent=2)
        blocks.append(f"```json\n{payload}\n```")
    return "\n\n".join(blocks)


def build_prompt(request: ChatRequest) -> Tuple[str, Optional[str]]:
    """Convert OpenAI messages into a plain-text conversation prompt.

    Returns (conversation_prompt, system_prompt).
    """
    system_parts: List[str] = []
    conv_lines: List[str] = []

    call_id_to_name: Dict[str, str] = {}
    for msg in request.messages:
        if msg.get("role") == "assistant":
            for tc in msg.get("tool_calls") or []:
                cid = tc.get("id")
                name = ((tc.get("function") or {}).get("name")) if isinstance(tc, dict) else None
                if cid and name:
                    call_id_to_name[cid] = name

    for msg in request.messages:
        role = msg.get("role", "")
        text = _content_to_text(msg.get("content"))

        if role == "system":
            system_parts.append(text)
        elif role == "user":
            conv_lines.append(f"User: {text}")
        elif role == "assistant":
            tcs = msg.get("tool_calls") or []
            serialized = _serialize_assistant_tool_calls(tcs) if tcs else ""
            combined = "\n\n".join(p for p in (text, serialized) if p)
            conv_lines.append(f"Assistant: {combined}")
        elif role == "tool":
            cid = msg.get("tool_call_id") or ""
            name = call_id_to_name.get(cid) or msg.get("name") or cid or "tool"
            conv_lines.append(f"Tool Result [{name}]: {text}")
        else:
            raise OpenAIError(
                f"Unsupported message role: {role!r}",
                param="messages",
            )

    system_prompt: Optional[str] = "\n\n".join(system_parts) if system_parts else None

    if request.tools:
        tool_specs = json.dumps(
            [
                {
                    "name": t.function.name,
                    "description": t.function.description,
                    "parameters": t.function.parameters,
                }
                for t in request.tools
            ],
            indent=2,
        )
        tool_block = _TOOL_BLOCK_TEMPLATE.format(tool_specs=tool_specs)
        system_prompt = (
            (system_prompt + "\n\n" + tool_block) if system_prompt else tool_block
        )

    if system_prompt is not None and len(system_prompt.encode("utf-8")) > MAX_SYSTEM_PROMPT_BYTES:
        raise OpenAIError(
            f"System prompt exceeds {MAX_SYSTEM_PROMPT_BYTES} bytes "
            "(argv limit). Shorten the system messages or tool specs.",
            status=413,
            error_type="invalid_request_error",
            param="messages",
        )

    conversation = "\n\n".join(conv_lines)

    if LOG_PROMPTS:
        logger.debug(
            "system_prompt (%d chars):\n%s",
            len(system_prompt or ""),
            _sanitize_log(system_prompt or ""),
        )
        logger.debug(
            "conversation (%d chars):\n%s",
            len(conversation),
            _sanitize_log(conversation),
        )
    else:
        logger.debug(
            "prompt built: system=%d chars  conversation=%d chars",
            len(system_prompt or ""),
            len(conversation),
        )

    return conversation, system_prompt


# ---------------------------------------------------------------------------
# Claude CLI invocation
# ---------------------------------------------------------------------------


async def _run_claude(
    conversation: str,
    system_prompt: Optional[str],
    model: str,
    streaming: bool,
    has_tools: bool,
    cache_key: Optional[str],
) -> AsyncIterator[str]:
    """Invoke the Claude CLI and yield raw stdout lines.

    - streaming=True  -> --output-format stream-json --verbose (NDJSON)
    - streaming=False -> --output-format json (single JSON line)
    - has_tools=True  -> --allowedTools "" so Claude can't run built-in tools
    - cache_key       -> SHA-256(system_prompt); used to --resume prior session
    """
    base_flags = ["--dangerously-skip-permissions"]

    if streaming:
        cmd = [
            CLAUDE_BIN, "--print", "--model", model,
            "--output-format", "stream-json",
            "--verbose",
            "--include-partial-messages",
            *base_flags,
        ]
    else:
        cmd = [
            CLAUDE_BIN, "--print", "--model", model,
            "--output-format", "json",
            *base_flags,
        ]

    if has_tools:
        cmd += ["--allowedTools", ""]

    if system_prompt:
        cmd += ["--system-prompt", system_prompt]

    resume_id = _session_cache.get(cache_key) if cache_key else None
    if resume_id:
        cmd += ["--resume", resume_id]

    logger.info(
        "Claude CLI: model=%s streaming=%s conv_chars=%d resume=%s",
        _sanitize_log(model), streaming, len(conversation), bool(resume_id),
    )

    env = os.environ.copy()
    env["CLAUDE_HOME"] = os.environ.get(
        "CLAUDE_PROXY_HOME", os.path.expanduser("~/.claude-proxy")
    )
    env["CLAUDE_BASH_NO_LOGIN"] = "1"
    env["CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC"] = "1"

    async with _get_cli_semaphore():
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        if proc.stdin is None or proc.stdout is None or proc.stderr is None:
            raise RuntimeError("Failed to open subprocess pipes")

        try:
            proc.stdin.write(conversation.encode("utf-8"))
            await proc.stdin.drain()
        except (BrokenPipeError, ConnectionResetError):
            pass
        finally:
            try:
                proc.stdin.close()
            except Exception:
                pass

        loop = asyncio.get_running_loop()
        deadline = loop.time() + CLI_TIMEOUT_SECONDS
        captured_session_id: Optional[str] = None
        result_text: Optional[str] = None
        result_is_error = False

        async def _terminate() -> None:
            if proc.returncode is None:
                proc.terminate()
                try:
                    await asyncio.wait_for(proc.wait(), timeout=3)
                except asyncio.TimeoutError:
                    proc.kill()

        try:
            while True:
                remaining = deadline - loop.time()
                if remaining <= 0:
                    raise asyncio.TimeoutError()
                try:
                    raw_line = await asyncio.wait_for(
                        proc.stdout.readline(), timeout=remaining
                    )
                except asyncio.TimeoutError:
                    raise
                if not raw_line:
                    break
                line = raw_line.decode("utf-8", errors="replace").strip()
                if not line:
                    continue
                try:
                    event = json.loads(line)
                    if isinstance(event, dict):
                        sid = event.get("session_id")
                        if sid and isinstance(sid, str):
                            captured_session_id = sid
                        if event.get("type") == "result" and "result" in event:
                            result_text = event["result"]
                            result_is_error = bool(event.get("is_error"))
                except json.JSONDecodeError:
                    if LOG_PROMPTS:
                        logger.debug("Non-JSON line from Claude: %s", line[:120])
                yield line

            try:
                stderr_bytes = await asyncio.wait_for(
                    proc.stderr.read(), timeout=5
                )
            except asyncio.TimeoutError:
                stderr_bytes = b""
            stderr_text = stderr_bytes.decode("utf-8", errors="replace").strip()

            await proc.wait()
            if proc.returncode not in (0, None):
                # Surface the CLI's own error text on failure, regardless of
                # LOG_PROMPTS. Claude reports API/auth failures (e.g. a revoked
                # OAuth token) in the result event's `result` field rather than
                # on stderr, so log both to keep failures legible in the journal
                # without turning on full request/response body logging.
                detail = result_text if result_is_error else None
                logger.warning(
                    "Claude exited with code %d%s%s",
                    proc.returncode,
                    f" - {detail[:500]}" if detail else "",
                    f" - stderr: {stderr_text[:500]}" if stderr_text else "",
                )
                if cache_key:
                    _session_cache.invalidate(cache_key)
            else:
                if stderr_text:
                    logger.debug("Claude stderr: %s", stderr_text[:500])
                if cache_key and captured_session_id:
                    _session_cache.put(cache_key, captured_session_id)

        except asyncio.TimeoutError:
            logger.error("Claude CLI timed out after %.0fs", CLI_TIMEOUT_SECONDS)
            if cache_key:
                _session_cache.invalidate(cache_key)
            await _terminate()
            raise OpenAIError(
                f"Claude CLI timed out after {CLI_TIMEOUT_SECONDS:.0f}s",
                status=504,
                error_type="api_error",
            )

        except asyncio.CancelledError:
            logger.info("Client disconnected - terminating Claude subprocess")
            await _terminate()
            raise


# ---------------------------------------------------------------------------
# Output parsing
# ---------------------------------------------------------------------------

# Match ```json ... ``` fenced blocks, tolerant of missing trailing newline.
_JSON_FENCE_RE = re.compile(r"```json\s*([\s\S]*?)```", re.MULTILINE)


def _extract_tool_calls(text: str) -> Tuple[List[Dict[str, Any]], str]:
    """Parse ```json tool-call fenced blocks into OpenAI tool_calls format."""
    tool_calls: List[Dict[str, Any]] = []
    removed_spans: List[Tuple[int, int]] = []

    for match in _JSON_FENCE_RE.finditer(text):
        body = match.group(1).strip()
        try:
            parsed = json.loads(body)
        except json.JSONDecodeError:
            continue
        if not isinstance(parsed, dict) or "name" not in parsed:
            continue
        if "arguments" not in parsed and "parameters" not in parsed:
            continue

        args = parsed.get("arguments")
        if args is None:
            args = parsed.get("parameters", {})

        tool_calls.append(
            {
                "id": f"call_{uuid.uuid4().hex[:8]}",
                "type": "function",
                "function": {
                    "name": parsed["name"],
                    "arguments": args if isinstance(args, str) else json.dumps(args),
                },
            }
        )
        removed_spans.append((match.start(), match.end()))

    if not removed_spans:
        return [], text

    cleaned = text
    for start, end in reversed(removed_spans):
        cleaned = cleaned[:start] + cleaned[end:]
    return tool_calls, cleaned.strip()


def _collect_result_text(lines: List[str]) -> str:
    for line in reversed(lines):
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        if event.get("type") == "result" and "result" in event:
            return event["result"]

    for line in reversed(lines):
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        if event.get("type") == "assistant":
            msg = event.get("message", {})
            parts = [
                b.get("text", "")
                for b in msg.get("content", [])
                if b.get("type") == "text"
            ]
            if parts:
                return "".join(parts)
    return ""


# ---------------------------------------------------------------------------
# Response helpers
# ---------------------------------------------------------------------------


def _completion_id() -> str:
    return f"chatcmpl-{uuid.uuid4().hex[:12]}"


def _non_streaming_response(
    cid: str,
    model: str,
    created: int,
    content: str,
    tool_calls: List[Dict[str, Any]],
) -> Dict[str, Any]:
    message: Dict[str, Any] = {"role": "assistant", "content": content or None}
    finish_reason = "stop"
    if tool_calls:
        message["tool_calls"] = tool_calls
        finish_reason = "tool_calls"

    return {
        "id": cid,
        "object": "chat.completion",
        "created": created,
        "model": model,
        "choices": [{"index": 0, "message": message, "finish_reason": finish_reason}],
        "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
    }


def _sse(payload: Dict[str, Any]) -> str:
    return f"data: {json.dumps(payload)}\n\n"


def _chunk(
    cid: str,
    model: str,
    created: int,
    delta: Dict[str, Any],
    finish_reason: Optional[str] = None,
) -> Dict[str, Any]:
    return {
        "id": cid,
        "object": "chat.completion.chunk",
        "created": created,
        "model": model,
        "choices": [{"index": 0, "delta": delta, "finish_reason": finish_reason}],
    }


def _tool_calls_with_index(tool_calls: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for i, tc in enumerate(tool_calls):
        entry = {"index": i}
        entry.update(tc)
        out.append(entry)
    return out


# ---------------------------------------------------------------------------
# Streaming generators
# ---------------------------------------------------------------------------


async def _stream_text_only(
    conversation: str,
    system_prompt: Optional[str],
    model: str,
    cid: str,
    created: int,
    cache_key: Optional[str],
) -> AsyncIterator[str]:
    yield _sse(_chunk(cid, model, created, {"role": "assistant"}))

    emitted_len = 0
    try:
        async for line in _run_claude(
            conversation, system_prompt, model,
            streaming=True, has_tools=False, cache_key=cache_key,
        ):
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                continue
            if event.get("type") != "assistant":
                continue
            msg = event.get("message", {})
            full_text = "".join(
                b.get("text", "")
                for b in msg.get("content", [])
                if b.get("type") == "text"
            )
            if len(full_text) > emitted_len:
                delta_text = full_text[emitted_len:]
                emitted_len = len(full_text)
                yield _sse(_chunk(cid, model, created, {"content": delta_text}))
    except OpenAIError as err:
        yield _sse({"error": err.to_body()["error"]})
        yield "data: [DONE]\n\n"
        return

    yield _sse(_chunk(cid, model, created, {}, finish_reason="stop"))
    yield "data: [DONE]\n\n"


async def _stream_with_tools(
    conversation: str,
    system_prompt: Optional[str],
    model: str,
    cid: str,
    created: int,
    cache_key: Optional[str],
) -> AsyncIterator[str]:
    """Streaming with tools: buffer everything, then emit.

    Text can contain partial JSON fences that must be parsed atomically;
    streaming them token-by-token leaks raw tool-call JSON to clients.
    """
    yield _sse(_chunk(cid, model, created, {"role": "assistant"}))

    lines: List[str] = []
    try:
        async for line in _run_claude(
            conversation, system_prompt, model,
            streaming=True, has_tools=True, cache_key=cache_key,
        ):
            lines.append(line)
    except OpenAIError as err:
        yield _sse({"error": err.to_body()["error"]})
        yield "data: [DONE]\n\n"
        return

    full_text = _collect_result_text(lines)
    tool_calls, cleaned_text = _extract_tool_calls(full_text)
    finish_reason = "tool_calls" if tool_calls else "stop"

    if LOG_PROMPTS:
        logger.debug(
            "Response id=%s tool_calls=%d text_chars=%d\n%s",
            cid, len(tool_calls), len(cleaned_text), cleaned_text,
        )
    else:
        logger.info(
            "Response id=%s tool_calls=%d text_chars=%d",
            cid, len(tool_calls), len(cleaned_text),
        )

    if cleaned_text:
        yield _sse(_chunk(cid, model, created, {"content": cleaned_text}))

    if tool_calls:
        yield _sse(
            _chunk(
                cid, model, created,
                {"tool_calls": _tool_calls_with_index(tool_calls)},
            )
        )

    yield _sse(_chunk(cid, model, created, {}, finish_reason=finish_reason))
    yield "data: [DONE]\n\n"


# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------


def _require_api_key(authorization: Optional[str]) -> None:
    if not API_KEY:
        raise OpenAIError(
            "Proxy is not configured with an API_KEY. "
            "Run ./generate_api_key.py to create one.",
            status=500,
            error_type="api_error",
        )
    if not authorization or not authorization.startswith("Bearer "):
        raise OpenAIError(
            "Missing Authorization header. Expected 'Bearer <API_KEY>'.",
            status=401,
            error_type="invalid_request_error",
            code="invalid_api_key",
        )
    provided = authorization[len("Bearer "):].strip()
    if not secrets.compare_digest(provided, API_KEY):
        raise OpenAIError(
            "Invalid API key.",
            status=401,
            error_type="invalid_request_error",
            code="invalid_api_key",
        )


# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------

_health_cache: Tuple[float, bool] = (0.0, False)
_HEALTH_TTL = 30.0


async def _check_claude_cli() -> bool:
    global _health_cache
    ts, ok = _health_cache
    now = time.time()
    if now - ts < _HEALTH_TTL:
        return ok
    try:
        proc = await asyncio.create_subprocess_exec(
            CLAUDE_BIN, "--version",
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
        await asyncio.wait_for(proc.wait(), timeout=5)
        ok = proc.returncode == 0
    except (FileNotFoundError, asyncio.TimeoutError, OSError):
        ok = False
    _health_cache = (now, ok)
    return ok


# ---------------------------------------------------------------------------
# FastAPI application
# ---------------------------------------------------------------------------

app = FastAPI(title="Claude Code Proxy", version="2.0.0")


@app.middleware("http")
async def _body_size_limit(request: Request, call_next):
    # Fast-path: reject immediately if Content-Length header exceeds limit.
    length = request.headers.get("content-length")
    if length:
        try:
            if int(length) > MAX_REQUEST_BYTES:
                return JSONResponse(
                    status_code=413,
                    content={
                        "error": {
                            "message": f"Request body exceeds {MAX_REQUEST_BYTES} bytes",
                            "type": "invalid_request_error",
                            "code": "request_too_large",
                            "param": None,
                        }
                    },
                )
        except ValueError:
            pass

    # Enforce the limit by reading the full body.
    # Starlette's _CachedRequest.wrapped_receive replays request._body to
    # downstream handlers automatically when body() is used (not stream()).
    body = await request.body()
    if len(body) > MAX_REQUEST_BYTES:
        return JSONResponse(
            status_code=413,
            content={
                "error": {
                    "message": f"Request body exceeds {MAX_REQUEST_BYTES} bytes",
                    "type": "invalid_request_error",
                    "code": "request_too_large",
                    "param": None,
                }
            },
        )

    return await call_next(request)


@app.exception_handler(OpenAIError)
async def _openai_error_handler(request: Request, exc: OpenAIError):
    return JSONResponse(status_code=exc.status, content=exc.to_body())


@app.get("/v1/models")
async def list_models(authorization: Optional[str] = Header(None)) -> Dict[str, Any]:
    _require_api_key(authorization)
    now = int(time.time())
    return {
        "object": "list",
        "data": [
            {
                "id": m,
                "object": "model",
                "created": now,
                "owned_by": "anthropic",
            }
            for m in CLAUDE_MODELS
        ],
    }


@app.post("/v1/chat/completions")
async def chat_completions(
    request: ChatRequest,
    authorization: Optional[str] = Header(None),
):
    _require_api_key(authorization)

    model = request.model or DEFAULT_MODEL
    if model not in _CLAUDE_MODEL_SET:
        raise OpenAIError(
            f"Unknown model {model!r}. Allowed: {', '.join(CLAUDE_MODELS)}",
            param="model",
            code="model_not_found",
        )

    # Resolve tool_choice BEFORE build_prompt so that tool_choice="none"
    # suppresses tool spec injection into the system prompt.
    tool_choice = request.tool_choice
    if isinstance(tool_choice, str) and tool_choice == "none":
        has_tools = False
        request.tools = None
    else:
        has_tools = bool(request.tools)

    conversation, system_prompt = build_prompt(request)
    cid = _completion_id()
    created = int(time.time())
    cache_key = _session_key(system_prompt, request.user)

    logger.info(
        "Request id=%s model=%s stream=%s tools=%d",
        cid, _sanitize_log(model), request.stream, len(request.tools or []),
    )

    if request.stream:
        # Note: once StreamingResponse starts, the HTTP 200 header is already
        # sent. Errors that occur during streaming are emitted as SSE payloads
        # rather than HTTP error status codes.
        if has_tools:
            gen = _stream_with_tools(
                conversation, system_prompt, model, cid, created, cache_key
            )
        else:
            gen = _stream_text_only(
                conversation, system_prompt, model, cid, created, cache_key
            )
        return StreamingResponse(gen, media_type="text/event-stream")

    lines: List[str] = []
    async for line in _run_claude(
        conversation, system_prompt, model,
        streaming=False, has_tools=has_tools, cache_key=cache_key,
    ):
        lines.append(line)

    full_text = _collect_result_text(lines)
    tool_calls, cleaned_text = _extract_tool_calls(full_text)

    if LOG_PROMPTS:
        logger.debug(
            "Response id=%s tool_calls=%d text_chars=%d\n%s",
            cid, len(tool_calls), len(cleaned_text), cleaned_text,
        )
    else:
        logger.info(
            "Response id=%s tool_calls=%d text_chars=%d",
            cid, len(tool_calls), len(cleaned_text),
        )

    return JSONResponse(
        _non_streaming_response(cid, model, created, cleaned_text, tool_calls)
    )


@app.get("/health")
async def health() -> JSONResponse:
    ok = await _check_claude_cli()
    return JSONResponse(
        status_code=200 if ok else 503,
        content={
            "status": "ok" if ok else "degraded",
            "claude_cli": ok,
            "api_key_configured": bool(API_KEY),
        },
    )
